name: cicd-test

on:
  push:
    branches: [ release ]

jobs:
  build:
    name: my test
    runs-on: windows-latest
    steps:
      - name: release
        uses: actions/checkout@master
        
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      
      - name: set path1
        run: |
          cd setenv
          ./setenv.bat
          echo "set path1 success!" >> ../README.md
          git config --global user.email 1435679023@qq.com
          git config --global user.name marsggbo
          git add .
          git commit -m "path1-success" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: build checksyntax and run
        run: |
          cd src/main/java/demos/checksyntax/
          ./compile_checksyntax.bat
          ./run_checksyntax.bat /f test/test.sql /t mysql
          
      - name: build gettablecolumns and run
        run: |
          cd src/main/java/demos/gettablecolumns/
          ./compile_gettablecolumns.bat
          ./run_getResultColumn.bat
